server:
  port: 8002
spring:
  application:
    name: mango-backup
#    服务监控
  boot:
    admin:
      client:
        url: "http://localhost:8000"
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name} # 注册到 consul 的服务名称

mango:
  backup:
    datasource:
      host: localhost
      userName: root
      password: root
      database: mango


# 服务监控
management:
  endpoints:
    web:
      exposure:
        include: "*"