server:
  port: 8002
spring:
  application:
    name: mango-backup
#    服务监控
  boot:
    admin:
      client:
        url: "http://localhost:8000"


mango:
  backup:
    datasource:
      host: localhost
      userName: root
      password: root
      database: mango


# 服务监控
management:
  endpoints:
    web:
      exposure:
        include: "*"